services:
  nf-nhits:
    image: neuralforecast
    build:
      context: ./model-services/neuralforecast
      dockerfile: Dockerfile
    volumes:
      - arena-db:/models
    ports:
      - "8020:8000"
    environment:
      - MODEL_TYPE=nhits
    networks:
      - default

  nf-tsmixerx:
    image: neuralforecast
    volumes:
      - arena-db:/models
    ports:
      - "8021:8000"
    environment:
      - MODEL_TYPE=tsmixerx
    networks:
      - default

  nf-patchtst:
    image: neuralforecast
    volumes:
      - arena-db:/models
    ports:
      - "8022:8000"
    environment:
      - MODEL_TYPE=patchtst
    networks:
      - default
  nf-tft:
    image: neuralforecast
    volumes:
      - arena-db:/models
    ports:
      - "8023:8000"
    environment:
      - MODEL_TYPE=tft
    networks:
      - default
  nf-tide:
    image: neuralforecast
    volumes:
      - arena-db:/models
    ports:
      - "8024:8000"
    environment:
      - MODEL_TYPE=tide
    networks:
      - default
  nf-lstm:
    image: neuralforecast
    volumes:
      - arena-db:/models
    ports:
      - "8025:8000"
    environment:
      - MODEL_TYPE=lstm
    networks:
      - default
volumes:
  arena-db:
    name: arena-db